version: "3.7"

services:

  caddy:
    image: caddy:2.1.1-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:2019:2019
    volumes:
      - ./data:/data
      - ./config:/config
      - ./logs:/logs
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy
